CONFIG = {}
CONFIG['DATASET_SOURCE_DIR'] = '/media/ubuntu/DATA/PARKING_239/DATA'
CONFIG['DATASET_WORKING_DIR'] = '/media/ubuntu/DATA/PARKING_239/WORK'
CONFIG['TARGET_IMAGE_SIZE'] = (224, 224)
CONFIG['ORIGINAL_IMAGE_SIZE'] = (640, 480)
CONFIG['DATASET_MEAN_STD_NUMBER'] = 20000
CONFIG['MEAN_STDEV_DIRECTORY'] = '/media/ubuntu/DATA/PARKING_239/WORK'
CONFIG['PREDICT_MODEL_NAME'] = 'parking-1-300'